// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mail.proto

package mail

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AttendeeConfirmationDetail struct {
	Name                  string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EventURL              string   `protobuf:"bytes,2,opt,name=eventURL,proto3" json:"eventURL,omitempty"`
	EventName             string   `protobuf:"bytes,3,opt,name=eventName,proto3" json:"eventName,omitempty"`
	EventCoverImage       string   `protobuf:"bytes,4,opt,name=eventCoverImage,proto3" json:"eventCoverImage,omitempty"`
	EventDateTime         string   `protobuf:"bytes,5,opt,name=eventDateTime,proto3" json:"eventDateTime,omitempty"`
	EventFullVenue        string   `protobuf:"bytes,6,opt,name=eventFullVenue,proto3" json:"eventFullVenue,omitempty"`
	EventOrganizerCompany string   `protobuf:"bytes,7,opt,name=eventOrganizerCompany,proto3" json:"eventOrganizerCompany,omitempty"`
	ConfirmationURL       string   `protobuf:"bytes,8,opt,name=confirmationURL,proto3" json:"confirmationURL,omitempty"`
	EmailId               string   `protobuf:"bytes,9,opt,name=emailId,proto3" json:"emailId,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *AttendeeConfirmationDetail) Reset()         { *m = AttendeeConfirmationDetail{} }
func (m *AttendeeConfirmationDetail) String() string { return proto.CompactTextString(m) }
func (*AttendeeConfirmationDetail) ProtoMessage()    {}
func (*AttendeeConfirmationDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0}
}

func (m *AttendeeConfirmationDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttendeeConfirmationDetail.Unmarshal(m, b)
}
func (m *AttendeeConfirmationDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttendeeConfirmationDetail.Marshal(b, m, deterministic)
}
func (m *AttendeeConfirmationDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttendeeConfirmationDetail.Merge(m, src)
}
func (m *AttendeeConfirmationDetail) XXX_Size() int {
	return xxx_messageInfo_AttendeeConfirmationDetail.Size(m)
}
func (m *AttendeeConfirmationDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_AttendeeConfirmationDetail.DiscardUnknown(m)
}

var xxx_messageInfo_AttendeeConfirmationDetail proto.InternalMessageInfo

func (m *AttendeeConfirmationDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AttendeeConfirmationDetail) GetEventURL() string {
	if m != nil {
		return m.EventURL
	}
	return ""
}

func (m *AttendeeConfirmationDetail) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *AttendeeConfirmationDetail) GetEventCoverImage() string {
	if m != nil {
		return m.EventCoverImage
	}
	return ""
}

func (m *AttendeeConfirmationDetail) GetEventDateTime() string {
	if m != nil {
		return m.EventDateTime
	}
	return ""
}

func (m *AttendeeConfirmationDetail) GetEventFullVenue() string {
	if m != nil {
		return m.EventFullVenue
	}
	return ""
}

func (m *AttendeeConfirmationDetail) GetEventOrganizerCompany() string {
	if m != nil {
		return m.EventOrganizerCompany
	}
	return ""
}

func (m *AttendeeConfirmationDetail) GetConfirmationURL() string {
	if m != nil {
		return m.ConfirmationURL
	}
	return ""
}

func (m *AttendeeConfirmationDetail) GetEmailId() string {
	if m != nil {
		return m.EmailId
	}
	return ""
}

type AnyResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnyResponse) Reset()         { *m = AnyResponse{} }
func (m *AnyResponse) String() string { return proto.CompactTextString(m) }
func (*AnyResponse) ProtoMessage()    {}
func (*AnyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{1}
}

func (m *AnyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnyResponse.Unmarshal(m, b)
}
func (m *AnyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnyResponse.Marshal(b, m, deterministic)
}
func (m *AnyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnyResponse.Merge(m, src)
}
func (m *AnyResponse) XXX_Size() int {
	return xxx_messageInfo_AnyResponse.Size(m)
}
func (m *AnyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnyResponse proto.InternalMessageInfo

func (m *AnyResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AnyResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ForgotPasswordRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EmailId              string   `protobuf:"bytes,2,opt,name=emailId,proto3" json:"emailId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordRequest) Reset()         { *m = ForgotPasswordRequest{} }
func (m *ForgotPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordRequest) ProtoMessage()    {}
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{2}
}

func (m *ForgotPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordRequest.Unmarshal(m, b)
}
func (m *ForgotPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordRequest.Merge(m, src)
}
func (m *ForgotPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordRequest.Size(m)
}
func (m *ForgotPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordRequest proto.InternalMessageInfo

func (m *ForgotPasswordRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ForgotPasswordRequest) GetEmailId() string {
	if m != nil {
		return m.EmailId
	}
	return ""
}

type ForgotPasswordResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ResetToken           string   `protobuf:"bytes,2,opt,name=resetToken,proto3" json:"resetToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordResponse) Reset()         { *m = ForgotPasswordResponse{} }
func (m *ForgotPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordResponse) ProtoMessage()    {}
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{3}
}

func (m *ForgotPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordResponse.Unmarshal(m, b)
}
func (m *ForgotPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordResponse.Merge(m, src)
}
func (m *ForgotPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordResponse.Size(m)
}
func (m *ForgotPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordResponse proto.InternalMessageInfo

func (m *ForgotPasswordResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ForgotPasswordResponse) GetResetToken() string {
	if m != nil {
		return m.ResetToken
	}
	return ""
}

type Email struct {
	EmailId              string   `protobuf:"bytes,1,opt,name=emailId,proto3" json:"emailId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{4}
}

func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (m *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(m, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetEmailId() string {
	if m != nil {
		return m.EmailId
	}
	return ""
}

type VisitorDetail struct {
	Name                  string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EventURL              string    `protobuf:"bytes,2,opt,name=eventURL,proto3" json:"eventURL,omitempty"`
	EventName             string    `protobuf:"bytes,3,opt,name=eventName,proto3" json:"eventName,omitempty"`
	EventCoverImage       string    `protobuf:"bytes,4,opt,name=eventCoverImage,proto3" json:"eventCoverImage,omitempty"`
	EventDateTime         string    `protobuf:"bytes,5,opt,name=eventDateTime,proto3" json:"eventDateTime,omitempty"`
	EventFullVenue        string    `protobuf:"bytes,6,opt,name=eventFullVenue,proto3" json:"eventFullVenue,omitempty"`
	EventOrganizerCompany string    `protobuf:"bytes,7,opt,name=eventOrganizerCompany,proto3" json:"eventOrganizerCompany,omitempty"`
	Coordinates           []float64 `protobuf:"fixed64,8,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	EmailId               string    `protobuf:"bytes,9,opt,name=emailId,proto3" json:"emailId,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}  `json:"-"`
	XXX_unrecognized      []byte    `json:"-"`
	XXX_sizecache         int32     `json:"-"`
}

func (m *VisitorDetail) Reset()         { *m = VisitorDetail{} }
func (m *VisitorDetail) String() string { return proto.CompactTextString(m) }
func (*VisitorDetail) ProtoMessage()    {}
func (*VisitorDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{5}
}

func (m *VisitorDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitorDetail.Unmarshal(m, b)
}
func (m *VisitorDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitorDetail.Marshal(b, m, deterministic)
}
func (m *VisitorDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitorDetail.Merge(m, src)
}
func (m *VisitorDetail) XXX_Size() int {
	return xxx_messageInfo_VisitorDetail.Size(m)
}
func (m *VisitorDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitorDetail.DiscardUnknown(m)
}

var xxx_messageInfo_VisitorDetail proto.InternalMessageInfo

func (m *VisitorDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VisitorDetail) GetEventURL() string {
	if m != nil {
		return m.EventURL
	}
	return ""
}

func (m *VisitorDetail) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *VisitorDetail) GetEventCoverImage() string {
	if m != nil {
		return m.EventCoverImage
	}
	return ""
}

func (m *VisitorDetail) GetEventDateTime() string {
	if m != nil {
		return m.EventDateTime
	}
	return ""
}

func (m *VisitorDetail) GetEventFullVenue() string {
	if m != nil {
		return m.EventFullVenue
	}
	return ""
}

func (m *VisitorDetail) GetEventOrganizerCompany() string {
	if m != nil {
		return m.EventOrganizerCompany
	}
	return ""
}

func (m *VisitorDetail) GetCoordinates() []float64 {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *VisitorDetail) GetEmailId() string {
	if m != nil {
		return m.EmailId
	}
	return ""
}

type ReminderRequestDetail struct {
	Name                  string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EventURL              string    `protobuf:"bytes,2,opt,name=eventURL,proto3" json:"eventURL,omitempty"`
	EventName             string    `protobuf:"bytes,3,opt,name=eventName,proto3" json:"eventName,omitempty"`
	EventCoverImage       string    `protobuf:"bytes,4,opt,name=eventCoverImage,proto3" json:"eventCoverImage,omitempty"`
	EventDateTime         string    `protobuf:"bytes,5,opt,name=eventDateTime,proto3" json:"eventDateTime,omitempty"`
	EventFullVenue        string    `protobuf:"bytes,6,opt,name=eventFullVenue,proto3" json:"eventFullVenue,omitempty"`
	EventOrganizerCompany string    `protobuf:"bytes,7,opt,name=eventOrganizerCompany,proto3" json:"eventOrganizerCompany,omitempty"`
	PrintTicketURL        string    `protobuf:"bytes,8,opt,name=printTicketURL,proto3" json:"printTicketURL,omitempty"`
	DaysToStart           int32     `protobuf:"varint,9,opt,name=daysToStart,proto3" json:"daysToStart,omitempty"`
	Coordinates           []float64 `protobuf:"fixed64,10,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	EmailId               string    `protobuf:"bytes,11,opt,name=emailId,proto3" json:"emailId,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}  `json:"-"`
	XXX_unrecognized      []byte    `json:"-"`
	XXX_sizecache         int32     `json:"-"`
}

func (m *ReminderRequestDetail) Reset()         { *m = ReminderRequestDetail{} }
func (m *ReminderRequestDetail) String() string { return proto.CompactTextString(m) }
func (*ReminderRequestDetail) ProtoMessage()    {}
func (*ReminderRequestDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{6}
}

func (m *ReminderRequestDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReminderRequestDetail.Unmarshal(m, b)
}
func (m *ReminderRequestDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReminderRequestDetail.Marshal(b, m, deterministic)
}
func (m *ReminderRequestDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReminderRequestDetail.Merge(m, src)
}
func (m *ReminderRequestDetail) XXX_Size() int {
	return xxx_messageInfo_ReminderRequestDetail.Size(m)
}
func (m *ReminderRequestDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ReminderRequestDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ReminderRequestDetail proto.InternalMessageInfo

func (m *ReminderRequestDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReminderRequestDetail) GetEventURL() string {
	if m != nil {
		return m.EventURL
	}
	return ""
}

func (m *ReminderRequestDetail) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *ReminderRequestDetail) GetEventCoverImage() string {
	if m != nil {
		return m.EventCoverImage
	}
	return ""
}

func (m *ReminderRequestDetail) GetEventDateTime() string {
	if m != nil {
		return m.EventDateTime
	}
	return ""
}

func (m *ReminderRequestDetail) GetEventFullVenue() string {
	if m != nil {
		return m.EventFullVenue
	}
	return ""
}

func (m *ReminderRequestDetail) GetEventOrganizerCompany() string {
	if m != nil {
		return m.EventOrganizerCompany
	}
	return ""
}

func (m *ReminderRequestDetail) GetPrintTicketURL() string {
	if m != nil {
		return m.PrintTicketURL
	}
	return ""
}

func (m *ReminderRequestDetail) GetDaysToStart() int32 {
	if m != nil {
		return m.DaysToStart
	}
	return 0
}

func (m *ReminderRequestDetail) GetCoordinates() []float64 {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *ReminderRequestDetail) GetEmailId() string {
	if m != nil {
		return m.EmailId
	}
	return ""
}

type PublishedRequestDetail struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EventURL             string   `protobuf:"bytes,2,opt,name=eventURL,proto3" json:"eventURL,omitempty"`
	EventName            string   `protobuf:"bytes,3,opt,name=eventName,proto3" json:"eventName,omitempty"`
	EventCoverImage      string   `protobuf:"bytes,4,opt,name=eventCoverImage,proto3" json:"eventCoverImage,omitempty"`
	EventDateTime        string   `protobuf:"bytes,5,opt,name=eventDateTime,proto3" json:"eventDateTime,omitempty"`
	EventFullVenue       string   `protobuf:"bytes,6,opt,name=eventFullVenue,proto3" json:"eventFullVenue,omitempty"`
	OrganizerId          string   `protobuf:"bytes,7,opt,name=organizerId,proto3" json:"organizerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishedRequestDetail) Reset()         { *m = PublishedRequestDetail{} }
func (m *PublishedRequestDetail) String() string { return proto.CompactTextString(m) }
func (*PublishedRequestDetail) ProtoMessage()    {}
func (*PublishedRequestDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{7}
}

func (m *PublishedRequestDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishedRequestDetail.Unmarshal(m, b)
}
func (m *PublishedRequestDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishedRequestDetail.Marshal(b, m, deterministic)
}
func (m *PublishedRequestDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishedRequestDetail.Merge(m, src)
}
func (m *PublishedRequestDetail) XXX_Size() int {
	return xxx_messageInfo_PublishedRequestDetail.Size(m)
}
func (m *PublishedRequestDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishedRequestDetail.DiscardUnknown(m)
}

var xxx_messageInfo_PublishedRequestDetail proto.InternalMessageInfo

func (m *PublishedRequestDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PublishedRequestDetail) GetEventURL() string {
	if m != nil {
		return m.EventURL
	}
	return ""
}

func (m *PublishedRequestDetail) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *PublishedRequestDetail) GetEventCoverImage() string {
	if m != nil {
		return m.EventCoverImage
	}
	return ""
}

func (m *PublishedRequestDetail) GetEventDateTime() string {
	if m != nil {
		return m.EventDateTime
	}
	return ""
}

func (m *PublishedRequestDetail) GetEventFullVenue() string {
	if m != nil {
		return m.EventFullVenue
	}
	return ""
}

func (m *PublishedRequestDetail) GetOrganizerId() string {
	if m != nil {
		return m.OrganizerId
	}
	return ""
}

type TicketRequestDetail struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	TicketId             string   `protobuf:"bytes,2,opt,name=ticketId,proto3" json:"ticketId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TicketRequestDetail) Reset()         { *m = TicketRequestDetail{} }
func (m *TicketRequestDetail) String() string { return proto.CompactTextString(m) }
func (*TicketRequestDetail) ProtoMessage()    {}
func (*TicketRequestDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{8}
}

func (m *TicketRequestDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketRequestDetail.Unmarshal(m, b)
}
func (m *TicketRequestDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketRequestDetail.Marshal(b, m, deterministic)
}
func (m *TicketRequestDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketRequestDetail.Merge(m, src)
}
func (m *TicketRequestDetail) XXX_Size() int {
	return xxx_messageInfo_TicketRequestDetail.Size(m)
}
func (m *TicketRequestDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketRequestDetail.DiscardUnknown(m)
}

var xxx_messageInfo_TicketRequestDetail proto.InternalMessageInfo

func (m *TicketRequestDetail) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TicketRequestDetail) GetTicketId() string {
	if m != nil {
		return m.TicketId
	}
	return ""
}

type AbandonedRequestDetail struct {
	Name                  string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EventName             string    `protobuf:"bytes,3,opt,name=eventName,proto3" json:"eventName,omitempty"`
	EventCoverImage       string    `protobuf:"bytes,4,opt,name=eventCoverImage,proto3" json:"eventCoverImage,omitempty"`
	EventDateTime         string    `protobuf:"bytes,5,opt,name=eventDateTime,proto3" json:"eventDateTime,omitempty"`
	EventFullVenue        string    `protobuf:"bytes,6,opt,name=eventFullVenue,proto3" json:"eventFullVenue,omitempty"`
	EventOrganizerCompany string    `protobuf:"bytes,7,opt,name=eventOrganizerCompany,proto3" json:"eventOrganizerCompany,omitempty"`
	CheckoutURL           string    `protobuf:"bytes,8,opt,name=checkoutURL,proto3" json:"checkoutURL,omitempty"`
	TicketAmount          int32     `protobuf:"varint,10,opt,name=ticketAmount,proto3" json:"ticketAmount,omitempty"`
	Coordinates           []float64 `protobuf:"fixed64,2,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	EmailId               string    `protobuf:"bytes,9,opt,name=emailId,proto3" json:"emailId,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}  `json:"-"`
	XXX_unrecognized      []byte    `json:"-"`
	XXX_sizecache         int32     `json:"-"`
}

func (m *AbandonedRequestDetail) Reset()         { *m = AbandonedRequestDetail{} }
func (m *AbandonedRequestDetail) String() string { return proto.CompactTextString(m) }
func (*AbandonedRequestDetail) ProtoMessage()    {}
func (*AbandonedRequestDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{9}
}

func (m *AbandonedRequestDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AbandonedRequestDetail.Unmarshal(m, b)
}
func (m *AbandonedRequestDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AbandonedRequestDetail.Marshal(b, m, deterministic)
}
func (m *AbandonedRequestDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AbandonedRequestDetail.Merge(m, src)
}
func (m *AbandonedRequestDetail) XXX_Size() int {
	return xxx_messageInfo_AbandonedRequestDetail.Size(m)
}
func (m *AbandonedRequestDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_AbandonedRequestDetail.DiscardUnknown(m)
}

var xxx_messageInfo_AbandonedRequestDetail proto.InternalMessageInfo

func (m *AbandonedRequestDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AbandonedRequestDetail) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *AbandonedRequestDetail) GetEventCoverImage() string {
	if m != nil {
		return m.EventCoverImage
	}
	return ""
}

func (m *AbandonedRequestDetail) GetEventDateTime() string {
	if m != nil {
		return m.EventDateTime
	}
	return ""
}

func (m *AbandonedRequestDetail) GetEventFullVenue() string {
	if m != nil {
		return m.EventFullVenue
	}
	return ""
}

func (m *AbandonedRequestDetail) GetEventOrganizerCompany() string {
	if m != nil {
		return m.EventOrganizerCompany
	}
	return ""
}

func (m *AbandonedRequestDetail) GetCheckoutURL() string {
	if m != nil {
		return m.CheckoutURL
	}
	return ""
}

func (m *AbandonedRequestDetail) GetTicketAmount() int32 {
	if m != nil {
		return m.TicketAmount
	}
	return 0
}

func (m *AbandonedRequestDetail) GetCoordinates() []float64 {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *AbandonedRequestDetail) GetEmailId() string {
	if m != nil {
		return m.EmailId
	}
	return ""
}

type ConfirmationRequestDetail struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TicketNumber         string   `protobuf:"bytes,6,opt,name=ticketNumber,proto3" json:"ticketNumber,omitempty"`
	TicketPurchaseDate   string   `protobuf:"bytes,8,opt,name=ticketPurchaseDate,proto3" json:"ticketPurchaseDate,omitempty"`
	TicketAmount         int32    `protobuf:"varint,9,opt,name=ticketAmount,proto3" json:"ticketAmount,omitempty"`
	EmailId              string   `protobuf:"bytes,11,opt,name=emailId,proto3" json:"emailId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmationRequestDetail) Reset()         { *m = ConfirmationRequestDetail{} }
func (m *ConfirmationRequestDetail) String() string { return proto.CompactTextString(m) }
func (*ConfirmationRequestDetail) ProtoMessage()    {}
func (*ConfirmationRequestDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{10}
}

func (m *ConfirmationRequestDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationRequestDetail.Unmarshal(m, b)
}
func (m *ConfirmationRequestDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationRequestDetail.Marshal(b, m, deterministic)
}
func (m *ConfirmationRequestDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationRequestDetail.Merge(m, src)
}
func (m *ConfirmationRequestDetail) XXX_Size() int {
	return xxx_messageInfo_ConfirmationRequestDetail.Size(m)
}
func (m *ConfirmationRequestDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationRequestDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationRequestDetail proto.InternalMessageInfo

func (m *ConfirmationRequestDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConfirmationRequestDetail) GetTicketNumber() string {
	if m != nil {
		return m.TicketNumber
	}
	return ""
}

func (m *ConfirmationRequestDetail) GetTicketPurchaseDate() string {
	if m != nil {
		return m.TicketPurchaseDate
	}
	return ""
}

func (m *ConfirmationRequestDetail) GetTicketAmount() int32 {
	if m != nil {
		return m.TicketAmount
	}
	return 0
}

func (m *ConfirmationRequestDetail) GetEmailId() string {
	if m != nil {
		return m.EmailId
	}
	return ""
}

type CreationRequestDetail struct {
	OrganizerName        string   `protobuf:"bytes,1,opt,name=organizerName,proto3" json:"organizerName,omitempty"`
	EmailId              string   `protobuf:"bytes,2,opt,name=emailId,proto3" json:"emailId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreationRequestDetail) Reset()         { *m = CreationRequestDetail{} }
func (m *CreationRequestDetail) String() string { return proto.CompactTextString(m) }
func (*CreationRequestDetail) ProtoMessage()    {}
func (*CreationRequestDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{11}
}

func (m *CreationRequestDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreationRequestDetail.Unmarshal(m, b)
}
func (m *CreationRequestDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreationRequestDetail.Marshal(b, m, deterministic)
}
func (m *CreationRequestDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreationRequestDetail.Merge(m, src)
}
func (m *CreationRequestDetail) XXX_Size() int {
	return xxx_messageInfo_CreationRequestDetail.Size(m)
}
func (m *CreationRequestDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_CreationRequestDetail.DiscardUnknown(m)
}

var xxx_messageInfo_CreationRequestDetail proto.InternalMessageInfo

func (m *CreationRequestDetail) GetOrganizerName() string {
	if m != nil {
		return m.OrganizerName
	}
	return ""
}

func (m *CreationRequestDetail) GetEmailId() string {
	if m != nil {
		return m.EmailId
	}
	return ""
}

type EnquiryRequest struct {
	OrganizerId          string   `protobuf:"bytes,1,opt,name=organizerId,proto3" json:"organizerId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Company              string   `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty"`
	JobTitle             string   `protobuf:"bytes,5,opt,name=jobTitle,proto3" json:"jobTitle,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	CompanyWebsite       string   `protobuf:"bytes,7,opt,name=companyWebsite,proto3" json:"companyWebsite,omitempty"`
	Comments             string   `protobuf:"bytes,8,opt,name=comments,proto3" json:"comments,omitempty"`
	EventId              string   `protobuf:"bytes,9,opt,name=eventId,proto3" json:"eventId,omitempty"`
	EnquiryType          string   `protobuf:"bytes,10,opt,name=enquiryType,proto3" json:"enquiryType,omitempty"`
	EventName            string   `protobuf:"bytes,11,opt,name=eventName,proto3" json:"eventName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnquiryRequest) Reset()         { *m = EnquiryRequest{} }
func (m *EnquiryRequest) String() string { return proto.CompactTextString(m) }
func (*EnquiryRequest) ProtoMessage()    {}
func (*EnquiryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{12}
}

func (m *EnquiryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnquiryRequest.Unmarshal(m, b)
}
func (m *EnquiryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnquiryRequest.Marshal(b, m, deterministic)
}
func (m *EnquiryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnquiryRequest.Merge(m, src)
}
func (m *EnquiryRequest) XXX_Size() int {
	return xxx_messageInfo_EnquiryRequest.Size(m)
}
func (m *EnquiryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnquiryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnquiryRequest proto.InternalMessageInfo

func (m *EnquiryRequest) GetOrganizerId() string {
	if m != nil {
		return m.OrganizerId
	}
	return ""
}

func (m *EnquiryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnquiryRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *EnquiryRequest) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *EnquiryRequest) GetJobTitle() string {
	if m != nil {
		return m.JobTitle
	}
	return ""
}

func (m *EnquiryRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EnquiryRequest) GetCompanyWebsite() string {
	if m != nil {
		return m.CompanyWebsite
	}
	return ""
}

func (m *EnquiryRequest) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func (m *EnquiryRequest) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *EnquiryRequest) GetEnquiryType() string {
	if m != nil {
		return m.EnquiryType
	}
	return ""
}

func (m *EnquiryRequest) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

type BrochureRequest struct {
	OrganizerId          string   `protobuf:"bytes,1,opt,name=organizerId,proto3" json:"organizerId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Company              string   `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	CompanyWebsite       string   `protobuf:"bytes,6,opt,name=companyWebsite,proto3" json:"companyWebsite,omitempty"`
	Comments             string   `protobuf:"bytes,7,opt,name=comments,proto3" json:"comments,omitempty"`
	Address1             string   `protobuf:"bytes,8,opt,name=address1,proto3" json:"address1,omitempty"`
	Address2             string   `protobuf:"bytes,9,opt,name=address2,proto3" json:"address2,omitempty"`
	City                 string   `protobuf:"bytes,10,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,11,opt,name=country,proto3" json:"country,omitempty"`
	EventId              string   `protobuf:"bytes,12,opt,name=eventId,proto3" json:"eventId,omitempty"`
	EventName            string   `protobuf:"bytes,13,opt,name=eventName,proto3" json:"eventName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrochureRequest) Reset()         { *m = BrochureRequest{} }
func (m *BrochureRequest) String() string { return proto.CompactTextString(m) }
func (*BrochureRequest) ProtoMessage()    {}
func (*BrochureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{13}
}

func (m *BrochureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrochureRequest.Unmarshal(m, b)
}
func (m *BrochureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrochureRequest.Marshal(b, m, deterministic)
}
func (m *BrochureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrochureRequest.Merge(m, src)
}
func (m *BrochureRequest) XXX_Size() int {
	return xxx_messageInfo_BrochureRequest.Size(m)
}
func (m *BrochureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BrochureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BrochureRequest proto.InternalMessageInfo

func (m *BrochureRequest) GetOrganizerId() string {
	if m != nil {
		return m.OrganizerId
	}
	return ""
}

func (m *BrochureRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BrochureRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *BrochureRequest) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *BrochureRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *BrochureRequest) GetCompanyWebsite() string {
	if m != nil {
		return m.CompanyWebsite
	}
	return ""
}

func (m *BrochureRequest) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func (m *BrochureRequest) GetAddress1() string {
	if m != nil {
		return m.Address1
	}
	return ""
}

func (m *BrochureRequest) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *BrochureRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *BrochureRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *BrochureRequest) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *BrochureRequest) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func init() {
	proto.RegisterType((*AttendeeConfirmationDetail)(nil), "mail.AttendeeConfirmationDetail")
	proto.RegisterType((*AnyResponse)(nil), "mail.AnyResponse")
	proto.RegisterType((*ForgotPasswordRequest)(nil), "mail.ForgotPasswordRequest")
	proto.RegisterType((*ForgotPasswordResponse)(nil), "mail.ForgotPasswordResponse")
	proto.RegisterType((*Email)(nil), "mail.Email")
	proto.RegisterType((*VisitorDetail)(nil), "mail.VisitorDetail")
	proto.RegisterType((*ReminderRequestDetail)(nil), "mail.ReminderRequestDetail")
	proto.RegisterType((*PublishedRequestDetail)(nil), "mail.PublishedRequestDetail")
	proto.RegisterType((*TicketRequestDetail)(nil), "mail.TicketRequestDetail")
	proto.RegisterType((*AbandonedRequestDetail)(nil), "mail.AbandonedRequestDetail")
	proto.RegisterType((*ConfirmationRequestDetail)(nil), "mail.ConfirmationRequestDetail")
	proto.RegisterType((*CreationRequestDetail)(nil), "mail.CreationRequestDetail")
	proto.RegisterType((*EnquiryRequest)(nil), "mail.EnquiryRequest")
	proto.RegisterType((*BrochureRequest)(nil), "mail.BrochureRequest")
}

func init() { proto.RegisterFile("mail.proto", fileDescriptor_7cda5f053e74676b) }

var fileDescriptor_7cda5f053e74676b = []byte{
	// 999 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0x57, 0xdc, 0x26, 0x6d, 0x5e, 0x9a, 0x54, 0x3b, 0x6d, 0x22, 0x6f, 0x58, 0x41, 0x88, 0x56,
	0xa8, 0xa7, 0x4a, 0x2c, 0x88, 0x0b, 0x12, 0x4b, 0xe8, 0xb6, 0xa8, 0x02, 0x4a, 0x95, 0x86, 0xed,
	0xd9, 0xb1, 0x1f, 0xcd, 0x50, 0x7b, 0x26, 0x3b, 0x33, 0x2e, 0x84, 0x13, 0x5f, 0x83, 0x03, 0x1f,
	0x86, 0x0b, 0x7c, 0x09, 0xbe, 0x03, 0x77, 0x4e, 0x68, 0xfe, 0xd8, 0xb5, 0xbd, 0x4e, 0x0b, 0x7b,
	0xd8, 0xc3, 0x6a, 0x6f, 0x7e, 0xbf, 0x79, 0xf3, 0x9b, 0x37, 0xbf, 0xf7, 0x66, 0xe6, 0x19, 0x20,
	0x09, 0x68, 0x7c, 0xb8, 0x14, 0x5c, 0x71, 0xb2, 0xa9, 0xbf, 0xc7, 0x7f, 0x79, 0x30, 0x9c, 0x28,
	0x85, 0x2c, 0x42, 0x3c, 0xe2, 0xec, 0x7b, 0x2a, 0x92, 0x40, 0x51, 0xce, 0x9e, 0xa1, 0x0a, 0x68,
	0x4c, 0x08, 0x6c, 0xb2, 0x20, 0x41, 0xbf, 0x31, 0x6a, 0x1c, 0xb4, 0xa7, 0xe6, 0x9b, 0x0c, 0x61,
	0x1b, 0x6f, 0x90, 0xa9, 0xef, 0xa6, 0x5f, 0xfb, 0x9e, 0xc1, 0x73, 0x9b, 0x3c, 0x82, 0xb6, 0xf9,
	0x3e, 0xd3, 0x93, 0x36, 0xcc, 0xe0, 0x2d, 0x40, 0x0e, 0x60, 0xd7, 0x18, 0x47, 0xfc, 0x06, 0xc5,
	0x69, 0x12, 0x5c, 0xa1, 0xbf, 0x69, 0x7c, 0xaa, 0x30, 0x79, 0x0c, 0x5d, 0x03, 0x3d, 0x0b, 0x14,
	0xce, 0x68, 0x82, 0x7e, 0xd3, 0xf8, 0x95, 0x41, 0xf2, 0x01, 0xf4, 0x0c, 0x70, 0x92, 0xc6, 0xf1,
	0x73, 0x64, 0x29, 0xfa, 0x2d, 0xe3, 0x56, 0x41, 0xc9, 0xc7, 0xd0, 0x37, 0xc8, 0xb7, 0xe2, 0x2a,
	0x60, 0xf4, 0x67, 0x14, 0x47, 0x3c, 0x59, 0x06, 0x6c, 0xe5, 0x6f, 0x19, 0xf7, 0xfa, 0x41, 0x1d,
	0x6d, 0x58, 0x50, 0x44, 0x6f, 0x77, 0xdb, 0x46, 0x5b, 0x81, 0x89, 0x0f, 0x5b, 0xa8, 0xd5, 0x3c,
	0x8d, 0xfc, 0xb6, 0xf1, 0xc8, 0xcc, 0xf1, 0x53, 0xe8, 0x4c, 0xd8, 0x6a, 0x8a, 0x72, 0xc9, 0x99,
	0x44, 0x32, 0x80, 0x96, 0x54, 0x81, 0x4a, 0xa5, 0x13, 0xd4, 0x59, 0x9a, 0x20, 0x41, 0x29, 0xb5,
	0x20, 0x56, 0xd1, 0xcc, 0x1c, 0x4f, 0xa0, 0x7f, 0xc2, 0xc5, 0x15, 0x57, 0xe7, 0x81, 0x94, 0x3f,
	0x72, 0x11, 0x4d, 0xf1, 0x45, 0x8a, 0x52, 0x91, 0x1e, 0x78, 0x34, 0x72, 0x34, 0x1e, 0x8d, 0x8a,
	0x31, 0x78, 0xe5, 0x18, 0xce, 0x61, 0x50, 0xa5, 0xb8, 0x27, 0x9c, 0x77, 0x01, 0x04, 0x4a, 0x54,
	0x33, 0x7e, 0x8d, 0xcc, 0xd1, 0x15, 0x90, 0xf1, 0xfb, 0xd0, 0x3c, 0xd6, 0xe4, 0xc5, 0x45, 0x1b,
	0xe5, 0x45, 0xff, 0xf4, 0xa0, 0xfb, 0x9c, 0x4a, 0xaa, 0xb8, 0x78, 0x5b, 0x4a, 0x64, 0x04, 0x9d,
	0x90, 0x73, 0x11, 0x51, 0x16, 0x28, 0x94, 0xfe, 0xf6, 0x68, 0xe3, 0xa0, 0x31, 0x2d, 0x42, 0x77,
	0x94, 0xd0, 0xaf, 0x1b, 0xd0, 0x9f, 0x62, 0x42, 0x59, 0x84, 0xc2, 0x25, 0xff, 0xad, 0xa2, 0x9a,
	0x7d, 0x29, 0x28, 0x53, 0x33, 0x1a, 0x5e, 0xa3, 0xba, 0x3d, 0x9b, 0x15, 0x54, 0x2b, 0x1f, 0x05,
	0x2b, 0x39, 0xe3, 0x17, 0x2a, 0x10, 0xca, 0x68, 0xdb, 0x9c, 0x16, 0xa1, 0x6a, 0x6e, 0xe0, 0xce,
	0xdc, 0x74, 0xca, 0xb9, 0xf9, 0xc5, 0x83, 0xc1, 0x79, 0x3a, 0x8f, 0xa9, 0x5c, 0x60, 0xf4, 0x26,
	0x26, 0x67, 0x04, 0x1d, 0x9e, 0x49, 0x7f, 0x1a, 0xb9, 0x94, 0x14, 0xa1, 0xf1, 0x29, 0xec, 0x59,
	0xb5, 0xcb, 0xdb, 0x1f, 0x40, 0x2b, 0x95, 0x66, 0x8e, 0xbb, 0x5a, 0xac, 0xa5, 0x25, 0x50, 0xc6,
	0x3d, 0xbf, 0xa7, 0x72, 0x7b, 0xfc, 0x8f, 0x07, 0x83, 0xc9, 0x3c, 0x60, 0x11, 0x67, 0xff, 0x45,
	0xcd, 0x37, 0xed, 0x82, 0x58, 0x60, 0x78, 0xcd, 0xd3, 0x42, 0x2d, 0x17, 0x21, 0x32, 0x86, 0x1d,
	0x2b, 0xd4, 0x24, 0xe1, 0x29, 0x53, 0x3e, 0x98, 0x4a, 0x2e, 0x61, 0xd5, 0x52, 0xf6, 0xfe, 0xcf,
	0x35, 0xf3, 0x7b, 0x03, 0x1e, 0x16, 0x1b, 0x80, 0xfb, 0xf5, 0xcf, 0x23, 0x3a, 0x4b, 0x93, 0x39,
	0x0a, 0xa7, 0x47, 0x09, 0x23, 0x87, 0x40, 0xac, 0x7d, 0x9e, 0x8a, 0x70, 0x11, 0x48, 0xd4, 0x7a,
	0xba, 0xed, 0xd5, 0x8c, 0xbc, 0xb4, 0xcb, 0x76, 0xcd, 0x2e, 0xd7, 0x1f, 0xc7, 0x4b, 0xe8, 0x1f,
	0x09, 0xac, 0x09, 0xff, 0x31, 0x74, 0xf3, 0x9a, 0x3d, 0xbb, 0xdd, 0x47, 0x19, 0xbc, 0xe3, 0x09,
	0xfd, 0xc3, 0x83, 0xde, 0x31, 0x7b, 0x91, 0x52, 0xb1, 0xca, 0xde, 0xdf, 0xca, 0xc9, 0x68, 0xbc,
	0x74, 0x32, 0x72, 0xcd, 0xbc, 0x82, 0x66, 0xfb, 0xd0, 0x5c, 0x2e, 0x38, 0xcb, 0xea, 0xd5, 0x1a,
	0x7a, 0xe1, 0xd0, 0x55, 0x89, 0xad, 0xd1, 0xcc, 0xd4, 0xc7, 0xe5, 0x07, 0x3e, 0x9f, 0x51, 0x15,
	0x67, 0x65, 0x99, 0xdb, 0x9a, 0xcb, 0xc4, 0xe7, 0x84, 0xb7, 0x86, 0xae, 0x53, 0x37, 0xf9, 0x12,
	0xe7, 0x92, 0x2a, 0x74, 0x85, 0x57, 0x41, 0x35, 0x73, 0xc8, 0x93, 0x04, 0x99, 0x92, 0x2e, 0x1f,
	0xb9, 0x6d, 0x84, 0xd0, 0x65, 0x5a, 0xa8, 0x12, 0x6b, 0xea, 0x5d, 0xa3, 0xd5, 0x61, 0xb6, 0x5a,
	0xa2, 0x29, 0xc2, 0xf6, 0xb4, 0x08, 0x95, 0x4f, 0x65, 0xa7, 0x72, 0x2a, 0xc7, 0x7f, 0x7b, 0xb0,
	0xfb, 0x85, 0xe0, 0xe1, 0x22, 0x15, 0xf8, 0x7a, 0x95, 0xcc, 0xd5, 0x6a, 0xde, 0xad, 0x56, 0xeb,
	0x5e, 0xb5, 0xb6, 0x2a, 0x6a, 0x0d, 0x61, 0x3b, 0x88, 0x22, 0x81, 0x52, 0x7e, 0x98, 0x29, 0x99,
	0xd9, 0x85, 0xb1, 0x27, 0x4e, 0xca, 0xdc, 0xd6, 0xbb, 0x0a, 0xa9, 0x5a, 0x39, 0x11, 0xcd, 0xb7,
	0x8d, 0x3f, 0x65, 0x4a, 0xac, 0xb2, 0xda, 0x76, 0x66, 0x31, 0x27, 0x3b, 0xe5, 0x9c, 0x94, 0x14,
	0xef, 0x56, 0x14, 0x7f, 0xf2, 0xdb, 0x16, 0x74, 0xbe, 0x09, 0x68, 0x7c, 0x81, 0xe2, 0x86, 0x86,
	0x48, 0x4e, 0x60, 0xd7, 0x1d, 0xf3, 0xac, 0xed, 0x27, 0xa3, 0x43, 0xf3, 0x5b, 0xb0, 0xfe, 0x37,
	0x60, 0xf8, 0xc0, 0x79, 0x14, 0x5a, 0xd9, 0xaf, 0xa0, 0x57, 0xee, 0x2a, 0xc9, 0x3b, 0xd6, 0xa9,
	0xb6, 0x5d, 0x1d, 0x3e, 0xaa, 0x1f, 0x74, 0x64, 0x87, 0xb0, 0x73, 0x89, 0x71, 0xc8, 0x13, 0xb4,
	0x7d, 0x65, 0xc7, 0x7a, 0x1b, 0xa3, 0x6e, 0xf1, 0x4f, 0x60, 0xc7, 0x35, 0x97, 0xd6, 0x7f, 0xcf,
	0xba, 0x94, 0x1a, 0xce, 0xba, 0x79, 0x4f, 0xa1, 0x9b, 0xb5, 0x52, 0x76, 0xa2, 0x8b, 0xb9, 0xb6,
	0xbf, 0xaa, 0x23, 0x98, 0x40, 0x2f, 0x7f, 0xef, 0x2d, 0x83, 0xdb, 0x58, 0x7d, 0x17, 0x50, 0x47,
	0xf1, 0x29, 0x74, 0xec, 0x83, 0x69, 0xe7, 0x3f, 0xb4, 0x1e, 0x35, 0x6f, 0xe8, 0x9a, 0xf5, 0xf3,
	0x17, 0xb2, 0xb4, 0x7e, 0xfd, 0xbb, 0x59, 0x47, 0xf1, 0x25, 0x3c, 0x28, 0x66, 0xd8, 0xb2, 0xbc,
	0x67, 0xfd, 0xd6, 0x3e, 0x00, 0x6b, 0xc4, 0x9c, 0x2c, 0x97, 0x82, 0xdf, 0x04, 0x71, 0x49, 0xcc,
	0xda, 0x2b, 0x78, 0x0d, 0x41, 0xe6, 0xfb, 0x6a, 0x04, 0x9f, 0xc1, 0xde, 0x85, 0xfe, 0xe2, 0xc2,
	0x5d, 0xce, 0x96, 0x66, 0xdf, 0x55, 0x4f, 0xe9, 0xc2, 0xae, 0x9b, 0xff, 0x39, 0xf4, 0x8f, 0x7f,
	0x5a, 0xd0, 0xb9, 0x29, 0xa4, 0x57, 0x64, 0xd8, 0xaf, 0x5c, 0x67, 0x96, 0xa0, 0x6f, 0x5d, 0x2b,
	0x63, 0x35, 0x0c, 0xf3, 0x96, 0xf9, 0x1b, 0xff, 0xe8, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4d,
	0xa8, 0x7d, 0x57, 0x9b, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MailServiceClient is the client API for MailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MailServiceClient interface {
	ConfirmAttendee(ctx context.Context, in *AttendeeConfirmationDetail, opts ...grpc.CallOption) (*AnyResponse, error)
	ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error)
	WelcomeEmail(ctx context.Context, in *Email, opts ...grpc.CallOption) (*AnyResponse, error)
	VisitorEmail(ctx context.Context, in *VisitorDetail, opts ...grpc.CallOption) (*AnyResponse, error)
	ReminderEmail(ctx context.Context, in *ReminderRequestDetail, opts ...grpc.CallOption) (*AnyResponse, error)
	PublishedEmail(ctx context.Context, in *PublishedRequestDetail, opts ...grpc.CallOption) (*AnyResponse, error)
	TicketEmail(ctx context.Context, in *TicketRequestDetail, opts ...grpc.CallOption) (*AnyResponse, error)
	AbandonedEmail(ctx context.Context, in *AbandonedRequestDetail, opts ...grpc.CallOption) (*AnyResponse, error)
	ConfirmationEmail(ctx context.Context, in *ConfirmationRequestDetail, opts ...grpc.CallOption) (*AnyResponse, error)
	ApprovalEmail(ctx context.Context, in *CreationRequestDetail, opts ...grpc.CallOption) (*AnyResponse, error)
	CreationEmail(ctx context.Context, in *CreationRequestDetail, opts ...grpc.CallOption) (*AnyResponse, error)
	SponsorEnquiryEmail(ctx context.Context, in *EnquiryRequest, opts ...grpc.CallOption) (*AnyResponse, error)
	ExhibitorEnquiryEmail(ctx context.Context, in *EnquiryRequest, opts ...grpc.CallOption) (*AnyResponse, error)
	BrochureRequestEmail(ctx context.Context, in *BrochureRequest, opts ...grpc.CallOption) (*AnyResponse, error)
}

type mailServiceClient struct {
	cc *grpc.ClientConn
}

func NewMailServiceClient(cc *grpc.ClientConn) MailServiceClient {
	return &mailServiceClient{cc}
}

func (c *mailServiceClient) ConfirmAttendee(ctx context.Context, in *AttendeeConfirmationDetail, opts ...grpc.CallOption) (*AnyResponse, error) {
	out := new(AnyResponse)
	err := c.cc.Invoke(ctx, "/mail.MailService/ConfirmAttendee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error) {
	out := new(ForgotPasswordResponse)
	err := c.cc.Invoke(ctx, "/mail.MailService/ForgotPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) WelcomeEmail(ctx context.Context, in *Email, opts ...grpc.CallOption) (*AnyResponse, error) {
	out := new(AnyResponse)
	err := c.cc.Invoke(ctx, "/mail.MailService/WelcomeEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) VisitorEmail(ctx context.Context, in *VisitorDetail, opts ...grpc.CallOption) (*AnyResponse, error) {
	out := new(AnyResponse)
	err := c.cc.Invoke(ctx, "/mail.MailService/VisitorEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) ReminderEmail(ctx context.Context, in *ReminderRequestDetail, opts ...grpc.CallOption) (*AnyResponse, error) {
	out := new(AnyResponse)
	err := c.cc.Invoke(ctx, "/mail.MailService/ReminderEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) PublishedEmail(ctx context.Context, in *PublishedRequestDetail, opts ...grpc.CallOption) (*AnyResponse, error) {
	out := new(AnyResponse)
	err := c.cc.Invoke(ctx, "/mail.MailService/PublishedEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) TicketEmail(ctx context.Context, in *TicketRequestDetail, opts ...grpc.CallOption) (*AnyResponse, error) {
	out := new(AnyResponse)
	err := c.cc.Invoke(ctx, "/mail.MailService/TicketEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) AbandonedEmail(ctx context.Context, in *AbandonedRequestDetail, opts ...grpc.CallOption) (*AnyResponse, error) {
	out := new(AnyResponse)
	err := c.cc.Invoke(ctx, "/mail.MailService/AbandonedEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) ConfirmationEmail(ctx context.Context, in *ConfirmationRequestDetail, opts ...grpc.CallOption) (*AnyResponse, error) {
	out := new(AnyResponse)
	err := c.cc.Invoke(ctx, "/mail.MailService/ConfirmationEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) ApprovalEmail(ctx context.Context, in *CreationRequestDetail, opts ...grpc.CallOption) (*AnyResponse, error) {
	out := new(AnyResponse)
	err := c.cc.Invoke(ctx, "/mail.MailService/ApprovalEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) CreationEmail(ctx context.Context, in *CreationRequestDetail, opts ...grpc.CallOption) (*AnyResponse, error) {
	out := new(AnyResponse)
	err := c.cc.Invoke(ctx, "/mail.MailService/CreationEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) SponsorEnquiryEmail(ctx context.Context, in *EnquiryRequest, opts ...grpc.CallOption) (*AnyResponse, error) {
	out := new(AnyResponse)
	err := c.cc.Invoke(ctx, "/mail.MailService/SponsorEnquiryEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) ExhibitorEnquiryEmail(ctx context.Context, in *EnquiryRequest, opts ...grpc.CallOption) (*AnyResponse, error) {
	out := new(AnyResponse)
	err := c.cc.Invoke(ctx, "/mail.MailService/ExhibitorEnquiryEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) BrochureRequestEmail(ctx context.Context, in *BrochureRequest, opts ...grpc.CallOption) (*AnyResponse, error) {
	out := new(AnyResponse)
	err := c.cc.Invoke(ctx, "/mail.MailService/BrochureRequestEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailServiceServer is the server API for MailService service.
type MailServiceServer interface {
	ConfirmAttendee(context.Context, *AttendeeConfirmationDetail) (*AnyResponse, error)
	ForgotPassword(context.Context, *ForgotPasswordRequest) (*ForgotPasswordResponse, error)
	WelcomeEmail(context.Context, *Email) (*AnyResponse, error)
	VisitorEmail(context.Context, *VisitorDetail) (*AnyResponse, error)
	ReminderEmail(context.Context, *ReminderRequestDetail) (*AnyResponse, error)
	PublishedEmail(context.Context, *PublishedRequestDetail) (*AnyResponse, error)
	TicketEmail(context.Context, *TicketRequestDetail) (*AnyResponse, error)
	AbandonedEmail(context.Context, *AbandonedRequestDetail) (*AnyResponse, error)
	ConfirmationEmail(context.Context, *ConfirmationRequestDetail) (*AnyResponse, error)
	ApprovalEmail(context.Context, *CreationRequestDetail) (*AnyResponse, error)
	CreationEmail(context.Context, *CreationRequestDetail) (*AnyResponse, error)
	SponsorEnquiryEmail(context.Context, *EnquiryRequest) (*AnyResponse, error)
	ExhibitorEnquiryEmail(context.Context, *EnquiryRequest) (*AnyResponse, error)
	BrochureRequestEmail(context.Context, *BrochureRequest) (*AnyResponse, error)
}

func RegisterMailServiceServer(s *grpc.Server, srv MailServiceServer) {
	s.RegisterService(&_MailService_serviceDesc, srv)
}

func _MailService_ConfirmAttendee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttendeeConfirmationDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).ConfirmAttendee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/ConfirmAttendee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).ConfirmAttendee(ctx, req.(*AttendeeConfirmationDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_ForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).ForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/ForgotPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).ForgotPassword(ctx, req.(*ForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_WelcomeEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Email)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).WelcomeEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/WelcomeEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).WelcomeEmail(ctx, req.(*Email))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_VisitorEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitorDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).VisitorEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/VisitorEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).VisitorEmail(ctx, req.(*VisitorDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_ReminderEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReminderRequestDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).ReminderEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/ReminderEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).ReminderEmail(ctx, req.(*ReminderRequestDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_PublishedEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishedRequestDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).PublishedEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/PublishedEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).PublishedEmail(ctx, req.(*PublishedRequestDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_TicketEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TicketRequestDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).TicketEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/TicketEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).TicketEmail(ctx, req.(*TicketRequestDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_AbandonedEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbandonedRequestDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).AbandonedEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/AbandonedEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).AbandonedEmail(ctx, req.(*AbandonedRequestDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_ConfirmationEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmationRequestDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).ConfirmationEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/ConfirmationEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).ConfirmationEmail(ctx, req.(*ConfirmationRequestDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_ApprovalEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreationRequestDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).ApprovalEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/ApprovalEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).ApprovalEmail(ctx, req.(*CreationRequestDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_CreationEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreationRequestDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).CreationEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/CreationEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).CreationEmail(ctx, req.(*CreationRequestDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_SponsorEnquiryEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnquiryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SponsorEnquiryEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/SponsorEnquiryEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SponsorEnquiryEmail(ctx, req.(*EnquiryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_ExhibitorEnquiryEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnquiryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).ExhibitorEnquiryEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/ExhibitorEnquiryEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).ExhibitorEnquiryEmail(ctx, req.(*EnquiryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_BrochureRequestEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrochureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).BrochureRequestEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/BrochureRequestEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).BrochureRequestEmail(ctx, req.(*BrochureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MailService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mail.MailService",
	HandlerType: (*MailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfirmAttendee",
			Handler:    _MailService_ConfirmAttendee_Handler,
		},
		{
			MethodName: "ForgotPassword",
			Handler:    _MailService_ForgotPassword_Handler,
		},
		{
			MethodName: "WelcomeEmail",
			Handler:    _MailService_WelcomeEmail_Handler,
		},
		{
			MethodName: "VisitorEmail",
			Handler:    _MailService_VisitorEmail_Handler,
		},
		{
			MethodName: "ReminderEmail",
			Handler:    _MailService_ReminderEmail_Handler,
		},
		{
			MethodName: "PublishedEmail",
			Handler:    _MailService_PublishedEmail_Handler,
		},
		{
			MethodName: "TicketEmail",
			Handler:    _MailService_TicketEmail_Handler,
		},
		{
			MethodName: "AbandonedEmail",
			Handler:    _MailService_AbandonedEmail_Handler,
		},
		{
			MethodName: "ConfirmationEmail",
			Handler:    _MailService_ConfirmationEmail_Handler,
		},
		{
			MethodName: "ApprovalEmail",
			Handler:    _MailService_ApprovalEmail_Handler,
		},
		{
			MethodName: "CreationEmail",
			Handler:    _MailService_CreationEmail_Handler,
		},
		{
			MethodName: "SponsorEnquiryEmail",
			Handler:    _MailService_SponsorEnquiryEmail_Handler,
		},
		{
			MethodName: "ExhibitorEnquiryEmail",
			Handler:    _MailService_ExhibitorEnquiryEmail_Handler,
		},
		{
			MethodName: "BrochureRequestEmail",
			Handler:    _MailService_BrochureRequestEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mail.proto",
}
